    const skuCategories={
      'WAL-LEAD':['Walking','Leads'],'WAL-COL':['Walking','Collars'],'WAL-HAR':['Walking','Harnesses'],
      'TOY-PLU':['Toys','Plush'],'TOY-RUB':['Toys','Rubber'],'TOY-ROP':['Toys','Rope & Tug'],'TOY-FET':['Toys','Fetch'],'TOY-PUP':['Toys','Puppy'],
      'BED-CUS':['Beds','Cushions'],'BED-MAT':['Beds','Mats'],'BED-BED':['Beds','Beds'],'BED-COV':['Beds','Covers'],
      'CLO-COA':['Clothing','Coats'],'CLO-JUM':['Clothing','Jumpers'],'FED-BOW':['Feeding','Bowls'],'FED-DSP':['Feeding','Feeders'],
      'CLN-SHA':['Grooming','Shampoo'],'CLN-GRM':['Grooming','Grooming']
    };
    function classifySku(sku){const parts=String(sku||'').trim().toUpperCase().split('-');const category=skuCategories[parts.slice(0,2).join('-')]||(parts[0]==='GFT'?['Gifts']:['Other']);return {type:category.join(' · '),brand:({HOP:'House of Paws',GOR:'Gor Pets',KNG:'KONG',DBN:'Doodlebone',PWH:'Pawfecthome'})[parts[2]]||''};}
    products.forEach(product=>Object.assign(product,classifySku(product.sku)));
    let selected='All';const grid=document.getElementById('products');const detail=document.getElementById('detail');
    function render(){const q=document.getElementById('search').value.toLowerCase().trim();const matches=products.filter(p=>(selected==='All'||p.type.startsWith(selected))&&(`${p.title} ${p.type} ${p.sku}`).toLowerCase().includes(q));grid.innerHTML=matches.length?matches.map(p=>`<article class="card"><a class="card-image" href="?product=${encodeURIComponent(p.id)}" data-open="${p.id}" aria-label="View ${p.title}"><img loading="lazy" src="${p.image}" alt="${p.title}" onerror="this.style.visibility='hidden'"></a><div class="card-body"><span class="card-type">${p.type}</span><h3>${p.title}</h3><div class="card-bottom"><span class="price">${p.price}</span><a class="small-link" href="?product=${encodeURIComponent(p.id)}" data-open="${p.id}">View details</a></div></div></article>`).join(''):'<p class="empty">No products match that search in this small preview.</p>'}
    function openProduct(id,push=true){const p=products.find(x=>x.id===id);if(!p)return;document.getElementById('detail-image').src=p.image;document.getElementById('detail-image').alt=p.title;document.getElementById('detail-type').textContent=p.type;document.getElementById('detail-title').textContent=p.title;document.getElementById('detail-price').textContent=p.price;document.getElementById('detail-description').textContent=p.description;document.getElementById('detail-action').innerHTML=p.ebay?`<a class="btn" href="${p.ebay}" target="_blank" rel="noopener noreferrer">See it on eBay</a>`:'<p class="demo">This sample product is not currently linked to an active eBay listing.</p>';detail.classList.add('open');document.body.style.overflow='hidden';if(push)history.pushState({product:id},'',`?product=${encodeURIComponent(id)}`);document.getElementById('close').focus()}
    function closeProduct(push=true){detail.classList.remove('open');document.body.style.overflow='';if(push)history.pushState({},'',location.pathname+location.hash)}
    document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open){e.preventDefault();openProduct(open.dataset.open)}const category=e.target.closest('[data-category]');if(category){selected=category.dataset.category;document.querySelectorAll('.filter').forEach(b=>{const active=b.dataset.filter===selected;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});render()}const filter=e.target.closest('[data-filter]');if(filter){selected=filter.dataset.filter;document.querySelectorAll('.filter').forEach(b=>{const active=b===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});render()}});
    document.getElementById('search').addEventListener('input',render);document.getElementById('close').addEventListener('click',()=>closeProduct());detail.addEventListener('click',e=>{if(e.target===detail)closeProduct()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&detail.classList.contains('open'))closeProduct()});window.addEventListener('popstate',()=>{const id=new URLSearchParams(location.search).get('product');id?openProduct(id,false):closeProduct(false)});
    const menu=document.getElementById('menu');menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',expanded);document.getElementById('nav').classList.toggle('open',expanded)});document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.getElementById('nav').classList.remove('open')}));render();const initial=new URLSearchParams(location.search).get('product');if(initial)openProduct(initial,false);
  